// DO NOT EDIT. This file is automatically generated by the generate-imports script.

import dynamic from "next/dynamic";
import { ComponentType } from "react";

type Import = {
  component: ComponentType;
  source: string;
};

export const imports: Record<string, Import> = {
  ["button-loading"]: {
    component: dynamic(
      () => import("@/foundations/ui/button/preview/button-loading.preview")
    ),
    source: `import { Button } from "@/foundations/ui/button/button";

export default function ButtonExample() {
  return <Button>Hello from dev meeting</Button>;
}
`,
  },
  ["button"]: {
    component: dynamic(
      () => import("@/foundations/ui/button/preview/button.preview")
    ),
    source: `import { Button } from "@/foundations/ui/button/button";

export default function ButtonExample() {
  return <Button>Click me</Button>;
}
`,
  },
  ["spinner"]: {
    component: dynamic(
      () => import("@/foundations/ui/spinner/preview/spinner.preview")
    ),
    source: `import { Spinner } from "@/foundations/ui/spinner/spinner";

export default function SpinnerExample() {
  return <Spinner />;
}
`,
  },
};
