// DO NOT EDIT. This file is automatically generated by the generate-imports script.
  
import dynamic from "next/dynamic";
import { ComponentType } from "react";

type Import = {
  component: ComponentType;
  source: string;
};

export const imports: Record<string, Import> = {
  ['button-loading']: {
    component: dynamic(
      () => import("@/foundations/ui/button/preview/button-loading.preview")
    ),
    source: `import { Button } from "@/foundations/ui/button/button";

export default function ButtonExample() {
  return <Button>Hello from dev meeting</Button>;
}
`},
  ['button']: {
    component: dynamic(
      () => import("@/foundations/ui/button/preview/button.preview")
    ),
    source: `import { Button } from "@/foundations/ui/button/button";

export default function ButtonExample() {
  return <Button>Click me</Button>;
}

/**
 * This is a very long comment to test scrolling functionality in the preview component.
 *
 * Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor
 * incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
 * exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute
 * irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
 * pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia
 * deserunt mollit anim id est laborum.
 *
 * Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque
 * laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi
 * architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas
 * sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione
 * voluptatem sequi nesciunt.
 *
 * Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci
 * velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam
 * aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem
 * ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?
 */
`},
  ['spinner']: {
    component: dynamic(
      () => import("@/foundations/ui/spinner/preview/spinner.preview")
    ),
    source: `import { Spinner } from "@/foundations/ui/spinner/spinner";

export default function SpinnerExample() {
  return <Spinner />;
}
`}
};
