// DO NOT EDIT. This file is automatically generated by the generate-imports script.
  
import dynamic from "next/dynamic";
import { ComponentType } from "react";

export const imports: Record<string, ComponentType> = {
  ['spinner']: dynamic(
    () => import("@/foundations/ui/spinner/preview/spinner.preview")
  ),
  ['button-loading']: dynamic(
    () => import("@/foundations/ui/button/preview/button-loading.preview")
  ),
  ['button']: dynamic(
    () => import("@/foundations/ui/button/preview/button.preview")
  )
};
