version: 2
updates:
  - package-ecosystem: 'npm'
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      patch-updates:
        update-types: patch
        patterns:
          - "*"
