app = 'significa-foundations'
primary_region = 'mad'

[build]

[deploy]
  strategy = "canary"
  wait_timeout = "1m"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.http_options.response]
    pristine = true

  [[http_service.checks]]
    grace_period = '10s'
    interval = '5s'
    timeout = '5s'
    method = 'GET'
    path = '/healthz'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
