name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  ci-cd:
    name: CI/CD
    permissions:
      contents: read
      packages: read
      deployments: write
    uses: significa/actions/.github/workflows/vercel-app.yaml@vercel-app-simple-strategy
    with:
      lint_command: npm run lint
      test_command: null
      staging_branch: null
      staging_domain: null
      production_branch: main
      # production_domain: ${{ vars.PRODUCTION_DOMAIN }}
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
